---
title: "625.661 Statistical Models and Regression Course Project"
author: "Mohammed Momin"
date: "5/9/2020"
output:
  html_document:
    df_print: paged
---


```{r}
library(MPV)#this library has all of the tables from the texbook
library(aod)
library(ggplot2)
library(olsrr)

Data=table.b6
y.lm<-lm(y ~ x1 + x2 + x3 + x4, data = Data)
summary(y.lm)
```

```{r}
y.lm<-lm(y ~ x1 + x2 + x3 + x4, data = Data)
all.pos=ols_step_all_possible(y.lm)
print(all.pos)
plot(all.pos)
```



```{r}
Data=table.b6
y.lm<-lm(y ~ x1 + x2 + x3 + x4, data = Data)
1-pchisq(0.0002098^2*23,23) #there is no lack of fit
(pr <- resid(y.lm)/(1 - lm.influence(y.lm)$hat))
sum(pr^2)
```

```{r}
Data=table.b6
#Data=Data[-c(25),] 

#Data=Data[-c(19),] 

y.lm<-lm(y ~ x1 + x2 + x3 + x4, data = Data)

par(mfrow = c(2, 2))
plot(y.lm)
par(mfrow = c(2, 2))
ols_plot_resid_stud(y.lm)
ols_plot_resid_lev(y.lm)
```


```{r}
ols_step_forward_p(y.lm, details = TRUE)
ols_step_backward_p(y.lm, details = TRUE)
ols_step_both_p(y.lm, details = TRUE)
```

```{r}
#summary(y.lm)
print('PRESS Statistic:')
PRESS(y.lm)
pint(y.lm)
#the PRESS statistic is very low therefore it has very good predictive performance
```

